// <auto-generated />
using CodersGear.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodersGear.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodersGear.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "T-shirts"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "Hoodies"
                        },
                        new
                        {
                            CategoryId = 3,
                            DisplayOrder = 3,
                            Name = "Mugs"
                        },
                        new
                        {
                            CategoryId = 4,
                            DisplayOrder = 4,
                            Name = "Accessoriess"
                        });
                });

            modelBuilder.Entity("CodersGear.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price100")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price50")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "A comfortable and stylish t-shirt for coders.",
                            ListPrice = 28.99m,
                            Price = 23.99m,
                            Price100 = 18.99m,
                            Price50 = 21.99m,
                            ProductName = "Coder's Gear T-shirt",
                            UPC = "123456789012"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "A cozy hoodie for coders to stay warm while coding.",
                            ListPrice = 44.99m,
                            Price = 39.99m,
                            Price100 = 32.99m,
                            Price50 = 36.99m,
                            ProductName = "Coder's Gear Hoodie",
                            UPC = "123456789013"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "A mug for coders to enjoy their favorite beverages while coding.",
                            ListPrice = 19.99m,
                            Price = 14.99m,
                            Price100 = 9.99m,
                            Price50 = 12.99m,
                            ProductName = "Coder's Gear Mug",
                            UPC = "123456789014"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            Description = "A protective laptop sleeve for coders to carry their laptops in style.",
                            ListPrice = 29.99m,
                            Price = 24.99m,
                            Price100 = 19.99m,
                            Price50 = 22.99m,
                            ProductName = "Coder's Gear Laptop Sleeve",
                            UPC = "123456789015"
                        });
                });

            modelBuilder.Entity("CodersGear.Models.Product", b =>
                {
                    b.HasOne("CodersGear.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
